from .add_api_view_tests import *
from .add_intra_move_view_tests import *
from .add_view_tests import *
from .delete_api_view_tests import *
from .edit_view_tests import *
from .index_view_tests import *
from .period_balance_view_tests import *
from .periodic_edit_view_tests import *
from .periodic_view_tests import *
from .search_view_tests import *
from .statistics_view_tests import *
from .tools_view_tests import *
