# Generated by Django 2.1.7 on 2019-09-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0004_auto_20190915_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='fixedCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
