# Generated by Django 2.2.5 on 2019-09-08 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('chargable', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('item', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('temp', models.BooleanField()),
                ('checked', models.BooleanField()),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Direction')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Genre')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Method')),
            ],
        ),
    ]
