# Generated by Django 2.2.5 on 2019-09-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='method',
            old_name='chargable',
            new_name='chargeable',
        ),
        migrations.RenameField(
            model_name='method',
            old_name='show_order',
            new_name='order',
        ),
    ]
