# Generated by Django 2.1.7 on 2019-09-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20190921_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachebackCheckedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='DigitalCheckedDate',
            new_name='CreditCheckedDate',
        ),
    ]
