# Generated by Django 2.1.7 on 2019-09-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0008_bankbalance_digitalcheckeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbalance',
            name='show_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digitalcheckeddate',
            name='show_order',
            field=models.IntegerField(default=0),
        ),
    ]
