# Generated by Django 2.1.7 on 2019-09-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0010_auto_20190921_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCostMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
