# Generated by Django 2.1.7 on 2019-11-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0013_auto_20190929_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='state',
            field=models.IntegerField(default=-1),
        ),
    ]
