# Generated by Django 2.1.7 on 2019-11-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0014_direction_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FixedCostPlan',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='state',
        ),
    ]
