# Generated by Django 2.1.7 on 2019-11-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0015_auto_20191122_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='show_order',
            field=models.IntegerField(default=-100),
        ),
    ]
