# Generated by Django 3.1.3 on 2020-11-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0016_genre_show_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='genre',
            new_name='category',
        ),
    ]
