# Generated by Django 3.1.3 on 2020-12-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0017_auto_20201128_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CachebackCheckedDate',
        ),
    ]
