# Generated by Django 3.1.4 on 2021-02-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0018_delete_cachebackcheckeddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_living_cost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_variable_cost',
            field=models.BooleanField(default=False),
        ),
    ]
