# Generated by Django 3.1.4 on 2021-02-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0019_auto_20210228_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='chargeable',
            field=models.BooleanField(default=0),
        ),
    ]
