# Generated by Django 3.1.4 on 2021-03-19 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0020_auto_20210228_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkeddate',
            name='method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='moneybook.method'),
        ),
    ]
