# Generated by Django 4.0 on 2022-09-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0021_auto_20210319_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='pre_checked',
            field=models.BooleanField(default=False),
        ),
    ]
