# Generated by Django 4.2.27 on 2026-02-08 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0022_data_pre_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moneybook.direction'),
        ),
    ]
