# Generated by Django 5.2.11 on 2026-02-08 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0023_category_default_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='default_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='moneybook.direction'),
        ),
        migrations.AlterField(
            model_name='checkeddate',
            name='method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='moneybook.method'),
        ),
        migrations.AlterField(
            model_name='data',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='moneybook.category'),
        ),
        migrations.AlterField(
            model_name='data',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='moneybook.direction'),
        ),
        migrations.AlterField(
            model_name='data',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='moneybook.method'),
        ),
    ]
