# Generated by Django 5.2.11 on 2026-02-11 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybook', '0024_alter_category_default_direction_alter_checkeddate_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('item', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('temp', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='moneybook.category')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='moneybook.direction')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='moneybook.method')),
            ],
        ),
    ]
