# Generated by Django 5.2.12 on 2026-03-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneybook", "0025_periodicdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodicdata",
            name="show_order",
            field=models.IntegerField(default=0),
        ),
    ]
