# Generated by Django 5.2.12 on 2026-04-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneybook", "0025_periodicdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="LivingCostMark",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("price", models.IntegerField()),
            ],
        ),
    ]
