# Generated by Django 6.0.5 on 2026-05-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneybook", "0026_livingcostmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livingcostmark",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
