from django.contrib.auth.views import LogoutView
from django.urls import path
from moneybook.views import (ActualCashApiView, AddApiView, AddIntraMoveApiView,
                             AddView, ApplyCheckApiView, CheckedDateApiView,
                             CreditCheckedDateApiView, CustomLoginView,
                             DataTableApiView, DeleteApiView, EditApiView,
                             EditView, IndexBalanceStatisticMiniApiView,
                             IndexChartDataApiView, IndexMonthView, IndexView,
                             LivingCostMarkApiView, NowBankApiView,
                             PeriodBalanceView, PreCheckedSummaryApiView,
                             PreCheckApiView, SearchView,
                             SeveralCheckedDateApiView, StatisticsMonthView,
                             StatisticsView, SuggestApiView, ToolsView,
                             UncheckedDataApiView)

app_name = 'moneybook'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<int:year>/<int:month>', IndexMonthView.as_view(), name='index_month'),
    path('add', AddView.as_view(), name='add'),
    path('statistics', StatisticsView.as_view(), name='statistics'),
    path('statistics/<int:year>', StatisticsMonthView.as_view(),
         name='statistics_month'),
    path('period_balances', PeriodBalanceView.as_view(), name='period_balances'),
    path('search', SearchView.as_view(), name='search'),
    path('tools', ToolsView.as_view(), name='tools'),
    path('edit/<int:pk>', EditView.as_view(), name='edit'),
    path('login', CustomLoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),

    # API
    path('api/add', AddApiView.as_view(), name='add_api'),
    path('api/add/intra-move', AddIntraMoveApiView.as_view(), name='add_intra_move_api'),
    path('api/suggest', SuggestApiView.as_view(), name='suggest_api'),
    path('api/edit/<int:pk>', EditApiView.as_view(), name='edit_api'),
    path('api/delete', DeleteApiView.as_view(), name='delete_api'),
    path('api/actual_cash', ActualCashApiView.as_view(), name='actual_cash_api'),
    path('api/checked_date', CheckedDateApiView.as_view(), name='checked_date_api'),
    path('api/credit_checked_date', CreditCheckedDateApiView.as_view(),
         name='credit_checked_date_api'),
    path('api/living_cost_mark', LivingCostMarkApiView.as_view(),
         name='living_cost_mark_api'),
    path('api/now_bank', NowBankApiView.as_view(), name='now_bank_api'),
    path('api/apply_check', ApplyCheckApiView.as_view(), name='apply_check_api'),
    path('api/pre_check', PreCheckApiView.as_view(), name='pre_check_api'),
    path('api/balance_statistic_mini', IndexBalanceStatisticMiniApiView.as_view(),
         name='balance_statistic_mini_api'),
    path('api/chart_container_data', IndexChartDataApiView.as_view(),
         name='chart_container_data_api'),
    path('api/data_table', DataTableApiView.as_view(), name='data_table_api'),
    path('api/several_checked_date', SeveralCheckedDateApiView.as_view(),
         name='several_checked_date_api'),
    path('api/unchecked_data', UncheckedDataApiView.as_view(), name='unchecked_data_api'),
    path('api/pre_checked_summary', PreCheckedSummaryApiView.as_view(),
         name='pre_checked_summary_api'),
]
