# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python lint with flake8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-import-order
        if [ -f build/requirements.txt ]; then pip install -r build/requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --ignore=E722,W503 --max-line-length=120 --exclude moneybook/migrations,__init__.py --show-source --statistics --import-order-style smarkets
